version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch  # Nome do nó
      - cluster.name=es-docker-cluster  # Nome do cluster
      - bootstrap.memory_lock=true  # Impede que o processo do Elasticsearch seja swapado
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Define o uso de memória para a JVM (mínimo e máximo 512MB)
      - http.cors.enabled=true  # Habilita CORS
      - http.cors.allow-origin="*"  # Permite requisições de qualquer origem (CORS)
      - discovery.type=single-node  # Configura o Elasticsearch como um nó único
    ulimits:
      memlock:  # Ajustes de limites de memória
        soft: -1  # Limite suave indefinido (sem limite)
        hard: -1  # Limite duro indefinido (sem limite)
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      - observabilidade

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200  # URL do Elasticsearch
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'  # Lista de hosts do Elasticsearch
    networks: 
      - observabilidade

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    container_name: metricbeat
    environment:
      - BEAT_STRICT_PERMS=false # Acessar as configurações sem restringir permissão de usuário
      # - BEAT_STRICT_PERMS=2 # Caso a configuração não suba os containers por conta de versão do docker
    user: "root:root"  # Executa o container como root
    volumes:  # Volumes montados para acessar o Docker Socket e o arquivo de configuração
      - /var/run/docker.sock:/var/run/docker.sock  # Permite o Metricbeat monitorar contêineres Docker
      - ./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure
    networks: 
      - observabilidade

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.17.0
    user: "root:root"
    container_name: heartbeat
    volumes:      
      - ./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    environment: 
      - setup.kibana.host=kibana:5601  # Define o Kibana como host para o setup do Heartbeat
      - BEAT_STRICT_PERMS=false # Acessar as configurações sem restringir permissão de usuário
      # - BEAT_STRICT_PERMS=2 # Caso a configuração não suba os containers por conta de versão do docker
    networks: 
      - observabilidade

  apm:
    image: docker.elastic.co/apm/apm-server-oss:7.17.0
    container_name: apm
    user: "root:root"
    volumes:      
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    environment:
      - BEAT_STRICT_PERMS=false # Acessar as configurações sem restringir permissão de usuário
      # - BEAT_STRICT_PERMS=2 # Caso a configuração não suba os containers por conta de versão do docker
    ports:
      - "8200:8200"
    restart: on-failure
    networks: 
      - observabilidade

  elastalert:
    image: jertel/elastalert2
    container_name: elastalert
    volumes:
      - ./elastalert/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/rules:/opt/elastalert/rules
    depends_on:
      - elasticsearch
    restart: on-failure
    networks:
      - observabilidade

networks:
  observabilidade:
    external: true
